import { useEffect, useState } from 'react'
import { ArrowLeft, Bot, Search, Send } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { posts } from '../../utils/mockData'
const chats=[{id:'welcome',name:'SocialStart Welcome Bot',avatar:'',msg:'Ask me how to use SocialStart!',time:'Now',unread:1},{id:'1',name:'Sofia Bell',avatar:posts[0].avatar,msg:'That light was unreal ✨',time:'2m',unread:0},{id:'2',name:'Mason Reed',avatar:posts[1].avatar,msg:'Your order ships tomorrow!',time:'1h',unread:0},{id:'3',name:'Amara Jones',avatar:posts[2].avatar,msg:'See you at the coast?',time:'Tue',unread:0}]
const answer=(question:string)=>{const q=question.toLowerCase();if(q.includes('profile')&&(q.includes('name')||q.includes('picture')||q.includes('photo')))return 'Open Settings, choose Edit profile, change your name or profile picture, then tap Save changes.';if(q.includes('post'))return 'Tap Post in the bottom navigation, choose what you want to create, add a title, and upload it.';if(q.includes('store')||q.includes('product'))return 'Open your profile, tap Online store, and use the store editor to add products.';if(q.includes('live'))return 'Tap Post, choose Go live, submit a stream title, then tap Start live stream.';if(q.includes('follow'))return 'Tap Follow beside a creator. Tap Following again whenever you want to unfollow.';if(q.includes('point'))return 'Open Post → One For One → Earn Social Points. Watch a full promo to earn one point.';return 'I can help with profiles, posting, stores, livestreams, following, and Social Points. What would you like to know?'}
export function InboxPage(){return <div className="inbox-page"><p className="eyebrow">YOUR CONVERSATIONS</p><h1>Inbox</h1><label className="search-box"><Search/><input placeholder="Search messages"/></label><div className="conversation-list">{chats.map(c=><Link to={`/inbox/${c.id}`} key={c.id}>{c.avatar?<img src={c.avatar}/>:<i className="bot-avatar"><Bot/></i>}<div><b>{c.name}</b><span>{c.msg}</span></div><aside><time>{c.time}</time>{c.unread>0&&<i>{c.unread}</i>}</aside></Link>)}</div></div>}
export function ConversationPage(){
 const {conversationId}=useParams(),isBot=conversationId==='welcome',chat=chats.find(item=>item.id===conversationId)||chats[1],key=`socialstart-messages-${conversationId}`
 const starter=isBot?[{text:'Welcome to SocialStart! Ask me a basic question about using the app.',mine:false}]:[{text:'I’m so glad you liked it!',mine:false},{text:'That light was unreal ✨',mine:true}]
 const [messages,setMessages]=useState<{text:string;mine:boolean}[]>(()=>{try{return JSON.parse(localStorage.getItem(key)||'null')||starter}catch{return starter}}),[text,setText]=useState('')
 useEffect(()=>{localStorage.setItem(key,JSON.stringify(messages))},[key,messages])
 const send=()=>{const value=text.trim();if(!value)return;setMessages(current=>[...current,{text:value,mine:true},...(isBot?[{text:answer(value),mine:false}]:[])]);setText('')}
 return <div className="chat-page"><header><Link to="/inbox"><ArrowLeft/></Link>{chat.avatar?<img src={chat.avatar}/>:<i className="bot-avatar"><Bot/></i>}<div><b>{chat.name}</b><span>{isBot?'Ready to help':'Active now'}</span></div></header><div className="messages"><time>Today</time>{messages.map((message,index)=><p key={index} className={message.mine?'mine':''}>{message.text}</p>)}</div><form onSubmit={event=>{event.preventDefault();send()}}><input value={text} onChange={event=>setText(event.target.value)} placeholder={isBot?'Ask a question…':'Write a message…'}/><button><Send/></button></form></div>
}
