import { Fragment, useMemo, useState } from 'react'
import { MapPin, Search, ShoppingBag, SlidersHorizontal, UserRound, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PostCard } from '../../components/PostCard'
import { useApp } from '../../context/AppContext'
import { posts, products, profiles } from '../../utils/mockData'
import { VideoTestAd } from '../../components/VideoTestAd'
import { CategoryPicker } from '../../components/CategoryPicker'
import { mediaUrl } from '../../lib/mediaStorage'
type Coordinates={latitude:number;longitude:number}
type MarketItem={id:string;title:string;price:number;image:string;stock:number;username:string;storeName:string;own?:boolean}
type DirectoryPerson={uid?:string;name:string;username:string;avatar:string;bio?:string;location?:string;lastActiveAt?:number}
const viewNumber=(value:string)=>{const number=parseFloat(value);return value.toUpperCase().includes('K')?number*1000:value.toUpperCase().includes('M')?number*1000000:number}
const distanceMiles=(from:Coordinates,latitude?:number,longitude?:number)=>{if(latitude===undefined||longitude===undefined)return Infinity;const radius=3958.8,toRadians=(degrees:number)=>degrees*Math.PI/180,latitudeDelta=toRadians(latitude-from.latitude),longitudeDelta=toRadians(longitude-from.longitude),a=Math.sin(latitudeDelta/2)**2+Math.cos(toRadians(from.latitude))*Math.cos(toRadians(latitude))*Math.sin(longitudeDelta/2)**2;return 2*radius*Math.asin(Math.sqrt(a))}
const readOwnProducts=():MarketItem[]=>{try{const accountId=localStorage.getItem('socialstart-active-account')||'guest',store=JSON.parse(localStorage.getItem(`socialstart-account-store-${accountId}`)||'{}') as {username?:string;storeName?:string;products?:{id:number;title:string;price:number;image:string;quantity:number}[]};return (store.products||[]).map(item=>({...item,image:mediaUrl(item.image),id:String(item.id),stock:item.quantity,username:store.username||'creator',storeName:store.storeName||'Your store',own:true}))}catch{return []}}
const readDirectoryPeople=():DirectoryPerson[]=>{
 const people=new Map<string,DirectoryPerson>()
 profiles.forEach(person=>people.set(person.username.toLowerCase(),person))
 for(let index=0;index<localStorage.length;index++){
  const key=localStorage.key(index)
  if(!key?.startsWith('socialstart-public-profile-'))continue
  try{
   const profile=JSON.parse(localStorage.getItem(key)||'{}') as Partial<DirectoryPerson>
   if(!profile.username)continue
   const username=profile.username.trim()
   people.set(username.toLowerCase(),{uid:profile.uid||key.slice('socialstart-public-profile-'.length),name:profile.name?.trim()||username,username,avatar:profile.avatar||'',bio:profile.bio||'',location:profile.location||'',lastActiveAt:profile.lastActiveAt})
  }catch{/* Ignore a damaged cached profile. */}
 }
 return [...people.values()].sort((a,b)=>a.name.localeCompare(b.name))
}
export function SearchPage(){
 const {followingUsernames,publicPosts,postMetrics}=useApp(),cachedLocation=()=>{try{return JSON.parse(localStorage.getItem('socialstart-location')||'null') as Coordinates|null}catch{return null}}
 const [feed,setFeed]=useState('Popular'),[query,setQuery]=useState(''),[coordinates,setCoordinates]=useState<Coordinates|null>(cachedLocation),[locationStatus,setLocationStatus]=useState(''),[showFilters,setShowFilters]=useState(false),[selectedCategory,setSelectedCategory]=useState(''),[mediaFilters,setMediaFilters]=useState({pictures:true,videos:true,livestreams:true})
 const fulfillmentExamples:MarketItem[]=[
  {id:'9101',title:'City Glow Print',price:24,image:'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?w=900&auto=format&fit=crop',stock:18,username:'sofiabell',storeName:'Sofia Selects'},
  {id:'9102',title:'Handmade Walnut Tray',price:48,image:'https://images.unsplash.com/photo-1618220179428-22790b461013?w=900&auto=format&fit=crop',stock:7,username:'masonmakes',storeName:'Mason Makes'},
 ]
 const marketItems:MarketItem[]=[...fulfillmentExamples,...products.map((item,index)=>({...item,username:profiles[index%profiles.length].username,storeName:`${profiles[index%profiles.length].name}'s store`})),...readOwnProducts()]
 const selectFeed=(next:string)=>{setFeed(next);if(next==='Nearby'&&!coordinates){if(!navigator.geolocation){setLocationStatus('Location is unavailable on this device.');return}setLocationStatus('Finding posts near you…');navigator.geolocation.getCurrentPosition(position=>{const nextCoordinates={latitude:position.coords.latitude,longitude:position.coords.longitude};setCoordinates(nextCoordinates);localStorage.setItem('socialstart-location',JSON.stringify(nextCoordinates));setLocationStatus('Sorted using your current location.')},()=>setLocationStatus('Allow location access to sort posts nearest to you.'),{enableHighAccuracy:false,timeout:10000,maximumAge:300000})}}
 const filtered=useMemo(()=>{const matching=[...publicPosts,...posts].filter(post=>{const type=post.mediaType||'image';return post.postType!=='story'&&(post.title+post.author+post.username).toLowerCase().includes(query.toLowerCase())&&(!selectedCategory||post.category===selectedCategory)&&(type==='live'?mediaFilters.livestreams:type==='video'?mediaFilters.videos:mediaFilters.pictures)});if(feed==='Following')return matching.filter(post=>followingUsernames.includes(post.username));if(feed==='Nearby'&&coordinates)return matching.sort((a,b)=>distanceMiles(coordinates,a.approximateLatitude,a.approximateLongitude)-distanceMiles(coordinates,b.approximateLatitude,b.approximateLongitude));if(feed==='Popular')return matching.sort((a,b)=>(viewNumber(b.views)+(postMetrics[b.id]?.views||0))-(viewNumber(a.views)+(postMetrics[a.id]?.views||0)));return matching},[coordinates,feed,followingUsernames,mediaFilters,postMetrics,publicPosts,query,selectedCategory])
 const visibleMarket=marketItems.filter(item=>(item.title+item.storeName+item.username).toLowerCase().includes(query.toLowerCase()))
 const activeAccountId=localStorage.getItem('socialstart-active-account')
 const visiblePeople=readDirectoryPeople().filter(person=>`${person.name} ${person.username}`.toLowerCase().includes(query.trim().replace(/^@/,'').toLowerCase()))
 const publicPeople=publicPosts.map(post=>({name:post.author,username:post.username,avatar:post.avatar})),followingPeople=[...profiles,...publicPeople].filter((person,index,all)=>followingUsernames.includes(person.username)&&all.findIndex(item=>item.username===person.username)===index)
 return <div className="feed-page"><section className="feed-intro"><p className="eyebrow">DISCOVER YOUR WORLD</p><h1>What’s happening<br/><em>around you?</em></h1><div className="feed-tabs">{['Users','Following','Popular','Nearby','Market'].map(item=><button onClick={()=>selectFeed(item)} className={feed===item?'active':''} key={item}>{item==='Users'&&<UserRound/>}{item==='Nearby'&&<MapPin/>}{item==='Market'&&<ShoppingBag/>}{item}</button>)}</div>{feed==='Nearby'&&locationStatus&&<p className="location-status">{locationStatus}</p>}<div className="search-filter-wrap"><label className="search-box"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={feed==='Users'?'Search people by name or username':feed==='Market'?'Search products or stores':'Search names, usernames, or posts'}/>{feed!=='Users'&&feed!=='Market'&&<button type="button" className={showFilters?'filter-trigger active':'filter-trigger'} onClick={()=>setShowFilters(!showFilters)} aria-label="Filter post types"><SlidersHorizontal/></button>}</label>{showFilters&&feed!=='Users'&&feed!=='Market'&&<div className="media-filter-popup"><button className="filter-close" onClick={()=>setShowFilters(false)} aria-label="Close filters"><X/></button><p className="eyebrow">SHOW IN SEARCH</p>{([['pictures','Pictures'],['videos','Videos'],['livestreams','Livestreams']] as const).map(([key,label])=><label key={key}><span>{label}</span><button type="button" className={mediaFilters[key]?'switch on':'switch'} onClick={()=>setMediaFilters(current=>({...current,[key]:!current[key]}))} aria-label={`${label} ${mediaFilters[key]?'on':'off'}`}><i/></button></label>)}<CategoryPicker value={selectedCategory} onChange={setSelectedCategory} label="Categories"/></div>}</div>{followingPeople.length>0&&feed!=='Users'&&<div className="following-stories" aria-label="Stories from people you follow">{followingPeople.map(person=><Link to={`/profile/${person.username}/story`} key={person.username}><span><img src={person.avatar} alt=""/><i/></span><small>{person.username}</small></Link>)}</div>}</section>
  <div className="feed-heading"><div><p className="eyebrow">{feed==='Users'?'PEOPLE DIRECTORY':feed==='Market'?'ALL STORES':`${feed.toUpperCase()} FEED`}</p><h2>{feed==='Users'?'Everyone on SocialStart':feed==='Following'?'People you follow':feed==='Nearby'?'Closest to you':feed==='Market'?'Shop the market':'Most viewed'}</h2></div></div>
  {feed==='Users'?(visiblePeople.length?<div className="user-directory">{visiblePeople.map(person=>{const own=Boolean(activeAccountId&&person.uid===activeAccountId),online=Date.now()-(person.lastActiveAt||0)<150000;return <Link to={own?'/profile':`/profile/${encodeURIComponent(person.uid||person.username)}`} key={person.uid||person.username}><span className="directory-avatar">{person.avatar?<img src={person.avatar} alt=""/>:<i>{person.name.slice(0,1)}</i>}<b className={online?'online':'offline'}/></span><div><strong>{person.name}</strong><small>{person.username}</small>{person.location&&<p><MapPin/> {person.location}</p>}</div></Link>})}</div>:<div className="feed-empty"><h3>No users found</h3><p>Try another name or username.</p></div>):feed==='Market'?(visibleMarket.length?<div className="market-grid">{visibleMarket.map(item=><Link to={item.own?'/store/alexmorgan/manage':`/store/${item.username}/product/${item.id}`} key={`${item.username}-${item.id}`}><img src={item.image}/><div><small>{item.storeName}</small><b>{item.title}</b><span>${item.price.toFixed(2)} · {item.stock} available</span></div></Link>)}</div>:<div className="feed-empty"><h3>No products found</h3></div>):filtered.length?<div className="feed-grid">{filtered.map((post,index)=><Fragment key={post.id}><PostCard post={post}/>{(index+1)%10===0&&<VideoTestAd placement="feed"/>}</Fragment>)}</div>:<div className="feed-empty"><h3>{feed==='Following'?'You aren’t following anyone yet':'No posts found'}</h3><p>{feed==='Following'?'Follow a creator from Popular or Nearby and their posts will appear here.':'Try another search.'}</p></div>}
 </div>
}
