import { useRef, useState } from 'react'
import { ImagePlus, Minus, Plus, Save, ShoppingBag, Store, Trash2 } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { products } from '../../utils/mockData'
import { useApp } from '../../context/AppContext'
import { scheduleCloudSave } from '../../lib/cloudSync'
import { uploadMedia } from '../../lib/mediaStorage'
import { formatCount, formatCurrency } from '../../lib/format'

type DraftProduct={id:number;title:string;quantity:number;price:number;image:string}
type AccountStore={username?:string;storeName?:string;description?:string;banner?:string;products?:DraftProduct[]}
const readAccountStores=()=>{const stores:AccountStore[]=[];for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(!key?.startsWith('socialstart-account-store-'))continue;try{const store=JSON.parse(localStorage.getItem(key)||'{}') as AccountStore;if(store.username)stores.push(store)}catch{/* Ignore damaged store data. */}}return stores}
const findAccountStore=(username?:string)=>{
 const direct=readAccountStores().find(store=>store.username===username)
 if(direct)return direct
 try{
  let accountId=username
  for(let index=0;index<localStorage.length;index++){
   const key=localStorage.key(index)
   if(!key?.startsWith('socialstart-public-profile-'))continue
   const publicProfile=JSON.parse(localStorage.getItem(key)||'{}') as {uid?:string;username?:string}
   if(publicProfile.uid===username||publicProfile.username===username){accountId=publicProfile.uid||key.slice('socialstart-public-profile-'.length);const cloudStore=JSON.parse(localStorage.getItem(`socialstart-account-store-${accountId}`)||'null') as AccountStore|null;return cloudStore||{username:publicProfile.username||username}}
  }
  if(accountId){const cloudStore=JSON.parse(localStorage.getItem(`socialstart-account-store-${accountId}`)||'null') as AccountStore|null;if(cloudStore)return cloudStore}
  const publicPosts=JSON.parse(localStorage.getItem('socialstart-public-posts')||'[]') as {username:string;ownerAccountId?:string}[]
  const postAccountId=publicPosts.find(post=>post.username===username||post.ownerAccountId===username)?.ownerAccountId
  if(postAccountId){const store=JSON.parse(localStorage.getItem(`socialstart-account-store-${postAccountId}`)||'null') as AccountStore|null;if(store)return store}
 }catch{/* Fall through to a fake store. */}
 return undefined
}
const persistentImage=async(file:File,maxWidth=1200,maxHeight=1200)=>{
 const source=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})
 const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const element=new Image();element.onload=()=>resolve(element);element.onerror=()=>reject(new Error('That image could not be loaded.'));element.src=source})
 const scale=Math.min(1,maxWidth/image.width,maxHeight/image.height),canvas=document.createElement('canvas')
 canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height)
 return canvas.toDataURL('image/jpeg',.76)
}

export function StorePage(){
 const {username}=useParams(),accountStore=findAccountStore(username),storeProducts=accountStore?.products||[]
 const heroStyle=accountStore?.banner?{backgroundImage:`linear-gradient(90deg,rgba(73,16,37,.84),rgba(73,16,37,.48)),url("${accountStore.banner}")`}:undefined
 if(accountStore)return <div className="store-page real-store"><section className={`store-hero${accountStore.banner?' public-store-banner':''}`} style={heroStyle}><p className="eyebrow">THE SHOP OF {username}</p><h1>{accountStore.storeName||`${username}'s store`}</h1><p>{accountStore.description||'Welcome to my SocialStart store.'}</p></section><div className="section-heading"><div><p className="eyebrow">THE COLLECTION</p><h2>Available products</h2></div><ShoppingBag/></div>{storeProducts.length?<div className="product-grid">{storeProducts.map(product=><Link to={`/store/${username}/product/${product.id}`} key={product.id}><img src={product.image}/><div><b>{product.title}</b><span>{formatCurrency(product.price)}</span></div><small>{formatCount(product.quantity)} available</small></Link>)}</div>:<div className="profile-empty"><ShoppingBag/><h3>No products yet</h3><p>This creator has not added anything to their store.</p></div>}</div>
 return <div className="store-page"><section className="store-hero"><p className="eyebrow">THE SHOP OF @{username}</p><h1>Sunday <em>Studio</em></h1><p>Objects for slower mornings and longer tables. Each piece is made by hand in small batches.</p><div><span>HANDMADE IN PORTLAND</span><span>SMALL BATCH</span><span>SHIPS WORLDWIDE</span></div></section><div className="section-heading"><div><p className="eyebrow">THE COLLECTION</p><h2>Made to be used</h2></div><ShoppingBag/></div><div className="product-grid">{products.map(p=><Link to={`/store/${username}/product/${p.id}`} key={p.id}><img src={p.image}/><div><b>{p.title}</b><span>{formatCurrency(p.price)}</span></div><small>{formatCount(p.stock)} available</small></Link>)}</div></div>
}

export function ProductDetailsPage(){const {productId,username}=useParams(),navigate=useNavigate(),accountStore=findAccountStore(username),realProduct=accountStore?.products?.find(item=>String(item.id)===productId),fakeProduct=products.find(x=>x.id===productId)||products[0],product=realProduct?{...realProduct,id:String(realProduct.id),stock:realProduct.quantity}:fakeProduct,{addToCart}=useApp(),[quantity,setQuantity]=useState(1);return <div className="product-detail"><img src={product.image}/><div><p className="eyebrow">{accountStore?.storeName||'SUNDAY STUDIO'} / PRODUCT</p><h1>{product.title}</h1><h2>{formatCurrency(product.price)}</h2><p>Available from {accountStore?.storeName||'Sunday Studio'} on SocialStart.</p><div className="quantity"><button onClick={()=>setQuantity(current=>Math.max(1,current-1))}><Minus/></button><span>{formatCount(quantity)}</span><button onClick={()=>setQuantity(current=>Math.min(product.stock,current+1))}><Plus/></button></div><button className="primary-btn wide" onClick={()=>{addToCart({id:`${username}-${product.id}`,title:product.title,price:product.price,image:product.image},quantity);navigate('/checkout')}}>Add to bag · {formatCurrency(product.price*quantity)}</button><small>{formatCount(product.stock)} in stock · Ships in 3–5 business days</small></div></div>}

export function CheckoutPage(){const {cart,updateCartQuantity,clearCart}=useApp(),[confirming,setConfirming]=useState(false),[complete,setComplete]=useState(false),total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);if(complete)return <div className="form-page centered"><div className="purchase-success"><ShoppingBag/><p className="eyebrow">ORDER CONFIRMED</p><h1>Thank you for your purchase.</h1><p>Your order has been placed and the seller will receive the details.</p><Link className="primary-btn" to="/search">Continue shopping</Link></div></div>;return <div className="form-page"><p className="eyebrow">SECURE CHECKOUT</p><h1>{confirming?'Confirm purchase':'Your bag'}</h1>{cart.length?cart.map(item=><div className="cart-row" key={item.id}><img src={item.image}/><div><b>{item.title}</b><div className="cart-quantity"><button onClick={()=>updateCartQuantity(item.id,item.quantity-1)}><Minus/></button><span>{item.quantity}</span><button onClick={()=>updateCartQuantity(item.id,item.quantity+1)}><Plus/></button></div></div><strong>${(item.price*item.quantity).toFixed(2)}</strong></div>):<div className="empty">Your bag is waiting for something beautiful.</div>}<div className="order-total"><span>Total</span><b>${total.toFixed(2)}</b></div>{confirming?<><div className="confirm-note">Confirm that you want to purchase these items for <b>${total.toFixed(2)}</b>.</div><button disabled={!cart.length} onClick={()=>{setComplete(true);clearCart()}} className="primary-btn wide">Confirm purchase</button><button onClick={()=>setConfirming(false)} className="checkout-back">Back to bag</button></>:<button disabled={!cart.length} onClick={()=>setConfirming(true)} className="primary-btn wide">Continue to confirm purchase</button>}</div>}

export function ManageStorePage(){
 const imageInput=useRef<HTMLInputElement>(null),bannerInput=useRef<HTMLInputElement>(null)
 const accountId=localStorage.getItem('socialstart-active-account')||'guest',detailsKey=`socialstart-account-store-${accountId}`
 const savedDetails=()=>{try{return JSON.parse(localStorage.getItem(detailsKey)||localStorage.getItem('socialstart-store-details')||'{}') as AccountStore}catch{return {}}}
 const initialDetails=savedDetails()
 const [storeName,setStoreName]=useState(initialDetails.storeName||''),[description,setDescription]=useState(initialDetails.description||''),[banner,setBanner]=useState(initialDetails.banner||''),[pendingBanner,setPendingBanner]=useState(''),[detailsSaved,setDetailsSaved]=useState(false),[bannerSaved,setBannerSaved]=useState(false),[bannerMessage,setBannerMessage]=useState(''),[title,setTitle]=useState(''),[quantity,setQuantity]=useState(''),[price,setPrice]=useState(''),[productImage,setProductImage]=useState(''),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState('')
 const [storeProducts,setStoreProducts]=useState<DraftProduct[]>(()=>initialDetails.products||(()=>{try{return JSON.parse(localStorage.getItem('socialstart-store-products')||'[]')}catch{return []}})())
 const username=(()=>{try{return JSON.parse(localStorage.getItem('socialstart-settings-profile')||'{}').username||'creator'}catch{return 'creator'}})()
 const saveStoreRecord=(updates:Partial<AccountStore>)=>{let current:AccountStore={};try{current=JSON.parse(localStorage.getItem(detailsKey)||'{}')}catch{/* Replace damaged store data. */}localStorage.setItem(detailsKey,JSON.stringify({...current,username,storeName:storeName.trim(),description:description.trim(),banner,...updates}));scheduleCloudSave()}
 const saveProducts=(next:DraftProduct[])=>{setStoreProducts(next);localStorage.setItem('socialstart-store-products',JSON.stringify(next));saveStoreRecord({products:next})}
 const chooseImage=async(file?:File)=>{if(!file)return;setUploading(true);setUploadError('');try{const localImage=await persistentImage(file);try{setProductImage(await uploadMedia(localImage,'products'))}catch{setProductImage(localImage)}}catch(error){setUploadError(error instanceof Error?error.message:'The image could not be loaded.')}finally{setUploading(false)}}
 const addProduct=()=>{if(!title||!quantity||!price||!productImage)return;saveProducts([...storeProducts,{id:Date.now(),title,quantity:Number(quantity),price:Number(price),image:productImage}]);setTitle('');setQuantity('');setPrice('');setProductImage('')}
 const saveDetails=()=>{saveStoreRecord({});setStoreName(storeName.trim());setDescription(description.trim());setDetailsSaved(true)}
 const chooseBanner=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas'),scale=Math.min(1,900/image.width,320/image.height);canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height);setPendingBanner(canvas.toDataURL('image/jpeg',.55));setBannerSaved(false);setBannerMessage('Banner ready — click Save banner.')} ;image.src=String(reader.result)};reader.readAsDataURL(file)}
 const saveBanner=async()=>{if(!pendingBanner)return;setUploading(true);setUploadError('');setBannerMessage('Saving banner…');let savedImage=pendingBanner;try{savedImage=await uploadMedia(pendingBanner,'store-banners')}catch{/* Keep the compressed persistent image when cloud upload is unavailable. */}setBanner(savedImage);saveStoreRecord({banner:savedImage,products:storeProducts});localStorage.setItem(`socialstart-store-banner-${accountId}`,savedImage);setPendingBanner('');setBannerSaved(true);setBannerMessage('Banner saved successfully.');setUploading(false)}
 const visibleBanner=pendingBanner||banner
 return <div className="manage-store-page"><section className={`store-setup-header store-banner-wide${visibleBanner?' has-banner':''}`} style={visibleBanner?{backgroundImage:`linear-gradient(90deg,rgba(73,16,37,.82),rgba(73,16,37,.5)),url("${visibleBanner}")`}:undefined}><div><p className="eyebrow">YOUR ONLINE STORE</p><h1>{storeName||'Build your store'}</h1><p>{description||'Add a name and a short line that tells shoppers what makes your store special.'}</p></div><div className="banner-actions"><input ref={bannerInput} hidden type="file" accept="image/*" onChange={event=>chooseBanner(event.target.files?.[0])}/><button type="button" className="banner-edit" onClick={()=>bannerInput.current?.click()}><ImagePlus/> Edit banner</button>{pendingBanner&&<button type="button" className="banner-save" onClick={saveBanner}><Save/> Save banner</button>}{bannerSaved&&<span>Banner saved</span>}</div></section>
  {uploadError&&<p className="camera-error">{uploadError}</p>}<section className="store-editor"><div className="store-form"><p className="eyebrow">STORE DETAILS</p><h2>Name your shop</h2><label className="field">Store name<input value={storeName} onChange={e=>{setStoreName(e.target.value);setDetailsSaved(false)}}/></label><label className="field">Line under store name<textarea value={description} onChange={e=>{setDescription(e.target.value);setDetailsSaved(false)}}/></label><button type="button" className="secondary-btn" onClick={saveDetails}><Save/> Save store details</button>{detailsSaved&&<p className="save-success">Store details saved.</p>}</div>
  <div className="product-form-panel"><p className="eyebrow">ADD A PRODUCT</p><h2>Your first listing</h2><input ref={imageInput} hidden type="file" accept="image/*" onChange={e=>chooseImage(e.target.files?.[0])}/><button type="button" disabled={uploading} onClick={()=>imageInput.current?.click()} className="product-image-drop">{productImage?<img src={productImage} alt="Product preview"/>:<><ImagePlus/><b>{uploading?'Uploading…':'Add product photo'}</b><span>Upload a clear image of your product</span></>}</button><label className="field">Product title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="field-pair"><label className="field">Quantity<input min="1" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label className="field">Price<input min="0" step="0.01" type="number" value={price} onChange={e=>setPrice(e.target.value)}/></label></div><button onClick={addProduct} disabled={uploading||!title||!quantity||!price||!productImage} className="primary-btn wide">Add product</button></div></section>
  <section className="store-products"><p className="eyebrow">YOUR PRODUCTS · {formatCount(storeProducts.length)}</p>{storeProducts.length===0?<div className="profile-empty"><ShoppingBag/><h3>No products yet</h3><p>Add your first product using the form above.</p></div>:<div className="draft-products">{storeProducts.map(product=><article key={product.id}><img src={product.image} alt=""/><div><b>{product.title}</b><span>{formatCount(product.quantity)} available</span></div><strong>{formatCurrency(product.price)}</strong><button className="delete-product" onClick={()=>saveProducts(storeProducts.filter(item=>item.id!==product.id))}><Trash2/> Delete</button></article>)}</div>}</section>
 </div>
}
