import { useRef, useState } from 'react'
import { ImagePlus, MessageCircle, Minus, Pencil, Plus, Save, ShoppingBag, Store, Trash2, X } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { products } from '../../utils/mockData'
import { useApp } from '../../context/AppContext'
import { saveStoreNow, scheduleCloudSave } from '../../lib/cloudSync'
import { mediaUrl, uploadMedia } from '../../lib/mediaStorage'
import { formatCount, formatCurrency } from '../../lib/format'

type DraftProduct={id:number;title:string;quantity:number;price:number;image:string;ship?:boolean;inPerson?:boolean;mediaFilter?:string;overlayText?:string;overlayX?:number;overlayY?:number}
type AccountStore={username?:string;storeName?:string;description?:string;banner?:string;products?:DraftProduct[]}
const exampleStores:Record<string,AccountStore>={
 sofiabell:{username:'sofiabell',storeName:'Sofia Selects',description:'Curated pieces shipped directly to you.',products:[{id:9101,title:'City Glow Print',quantity:18,price:24,image:'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?w=900&auto=format&fit=crop',ship:true,inPerson:false}]},
 masonmakes:{username:'masonmakes',storeName:'Mason Makes',description:'Handmade locally with meetup pickup available.',products:[{id:9102,title:'Handmade Walnut Tray',quantity:7,price:48,image:'https://images.unsplash.com/photo-1618220179428-22790b461013?w=900&auto=format&fit=crop',ship:false,inPerson:true}]},
}
const readAccountStores=()=>{const stores:AccountStore[]=[];for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(!key?.startsWith('socialstart-account-store-'))continue;try{const store=JSON.parse(localStorage.getItem(key)||'{}') as AccountStore;if(store.username)stores.push(store)}catch{/* Ignore damaged store data. */}}return stores}
const findAccountStore=(username?:string)=>{
 const direct=readAccountStores().find(store=>store.username===username)
 if(direct)return direct
 if(username&&exampleStores[username])return exampleStores[username]
 try{
  let accountId=username
  for(let index=0;index<localStorage.length;index++){
   const key=localStorage.key(index)
   if(!key?.startsWith('socialstart-public-profile-'))continue
   const publicProfile=JSON.parse(localStorage.getItem(key)||'{}') as {uid?:string;username?:string}
   if(publicProfile.uid===username||publicProfile.username===username){accountId=publicProfile.uid||key.slice('socialstart-public-profile-'.length);const cloudStore=JSON.parse(localStorage.getItem(`socialstart-account-store-${accountId}`)||'null') as AccountStore|null;return cloudStore||{username:publicProfile.username||username}}
  }
  if(accountId){const cloudStore=JSON.parse(localStorage.getItem(`socialstart-account-store-${accountId}`)||'null') as AccountStore|null;if(cloudStore)return cloudStore}
  const publicPosts=JSON.parse(localStorage.getItem('socialstart-public-posts')||'[]') as {username:string;ownerAccountId?:string}[]
  const postAccountId=publicPosts.find(post=>post.username===username||post.ownerAccountId===username)?.ownerAccountId
  if(postAccountId){const store=JSON.parse(localStorage.getItem(`socialstart-account-store-${postAccountId}`)||'null') as AccountStore|null;if(store)return store}
 }catch{/* Fall through to a fake store. */}
 return undefined
}
const persistentImage=async(file:File,maxWidth=720,maxHeight=720)=>{
 const source=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})
 const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const element=new Image();element.onload=()=>resolve(element);element.onerror=()=>reject(new Error('That image could not be loaded.'));element.src=source})
 const scale=Math.min(1,maxWidth/image.width,maxHeight/image.height),canvas=document.createElement('canvas')
 canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height)
 return canvas.toDataURL('image/jpeg',.6)
}

export function StorePage(){
 const {username}=useParams(),accountStore=findAccountStore(username),storeProducts=accountStore?.products||[]
 const heroStyle=accountStore?.banner?{backgroundImage:`linear-gradient(90deg,rgba(73,16,37,.84),rgba(73,16,37,.48)),url("${mediaUrl(accountStore.banner)}")`}:undefined
 if(accountStore)return <div className="store-page real-store"><section className={`store-hero${accountStore.banner?' public-store-banner':''}`} style={heroStyle}><p className="eyebrow">THE SHOP OF {username}</p><h1>{accountStore.storeName||`${username}'s store`}</h1><p>{accountStore.description||'Welcome to my SocialStart store.'}</p></section><div className="section-heading"><div><p className="eyebrow">THE COLLECTION</p><h2>Available products</h2></div><ShoppingBag/></div>{storeProducts.length?<div className="product-grid">{storeProducts.map(product=><Link to={`/store/${username}/product/${product.id}`} key={product.id}><div className="editable-media-preview"><img src={mediaUrl(product.image)} style={{filter:product.mediaFilter}}/>{product.overlayText&&<span style={{left:`${product.overlayX??50}%`,top:`${product.overlayY??50}%`}}>{product.overlayText}</span>}</div><div><b>{product.title}</b><span>{formatCurrency(product.price)}</span></div><small>{formatCount(product.quantity)} available · {[product.ship&&'Ship',product.inPerson&&'In person'].filter(Boolean).join(' / ')}</small></Link>)}</div>:<div className="profile-empty"><ShoppingBag/><h3>No products yet</h3><p>This creator has not added anything to their store.</p></div>}</div>
 return <div className="store-page"><section className="store-hero"><p className="eyebrow">THE SHOP OF @{username}</p><h1>Sunday <em>Studio</em></h1><p>Objects for slower mornings and longer tables. Each piece is made by hand in small batches.</p><div><span>HANDMADE IN PORTLAND</span><span>SMALL BATCH</span><span>SHIPS WORLDWIDE</span></div></section><div className="section-heading"><div><p className="eyebrow">THE COLLECTION</p><h2>Made to be used</h2></div><ShoppingBag/></div><div className="product-grid">{products.map(p=><Link to={`/store/${username}/product/${p.id}`} key={p.id}><img src={p.image}/><div><b>{p.title}</b><span>{formatCurrency(p.price)}</span></div><small>{formatCount(p.stock)} available</small></Link>)}</div></div>
}

export function ProductDetailsPage(){const {productId,username}=useParams(),navigate=useNavigate(),accountStore=findAccountStore(username),realProduct=accountStore?.products?.find(item=>String(item.id)===productId),fakeProduct=products.find(x=>x.id===productId)||products[0],product=realProduct?{...realProduct,id:String(realProduct.id),stock:realProduct.quantity}:fakeProduct,{addToCart}=useApp(),[quantity,setQuantity]=useState(1);const local=Boolean('inPerson' in product&&product.inPerson),ship=!('ship' in product)||Boolean(product.ship),productMedia=mediaUrl(product.image);return <div className="product-detail"><img src={productMedia}/><div><p className="eyebrow">{accountStore?.storeName||'SUNDAY STUDIO'} / PRODUCT</p><h1>{product.title}</h1><h2>{formatCurrency(product.price)}</h2><p>Available from {accountStore?.storeName||'Sunday Studio'} on SocialStart.</p><div className="quantity"><button onClick={()=>setQuantity(current=>Math.max(1,current-1))}><Minus/></button><span>{formatCount(quantity)}</span><button onClick={()=>setQuantity(current=>Math.min(product.stock,current+1))}><Plus/></button></div><button className="primary-btn wide" onClick={()=>{addToCart({id:`${username}-${product.id}`,title:product.title,price:product.price,image:productMedia,ship,inPerson:local,sellerUsername:username},quantity);navigate('/checkout')}}>Add to bag · {formatCurrency(product.price*quantity)}</button>{local&&<button className="secondary-btn wide" onClick={()=>navigate(`/inbox/${username}`)}><MessageCircle/> Message seller to arrange meetup</button>}<small>{formatCount(product.stock)} in stock · {[ship&&'Shipping',local&&'In-person meetup'].filter(Boolean).join(' or ')}</small></div></div>}

export function CheckoutPage(){
 const {cart,updateCartQuantity,clearCart}=useApp(),[confirming,setConfirming]=useState(false),[complete,setComplete]=useState(false),[address,setAddress]=useState<Record<string,string>>(()=>{try{return JSON.parse(localStorage.getItem('socialstart-settings-address')||'{}')}catch{return {}}})
 const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0),needsAddress=cart.some(item=>item.ship),addressReady=Boolean(address.street&&address.city&&address.region&&address.postalCode)
 if(complete)return <div className="form-page centered"><div className="purchase-success"><ShoppingBag/><p className="eyebrow">ORDER CONFIRMED</p><h1>Thank you for your purchase.</h1><p>Your order has been placed and the seller will receive the details.</p><Link className="primary-btn" to="/search">Continue shopping</Link></div></div>
 return <div className="form-page"><p className="eyebrow">SECURE CHECKOUT</p><h1>{confirming?'Confirm purchase':'Your bag'}</h1>{cart.length?cart.map(item=><div className="cart-row" key={item.id}><img src={item.image}/><div><b>{item.title}</b><small>{[item.ship&&'Ship',item.inPerson&&'In person'].filter(Boolean).join(' · ')}</small><div className="cart-quantity"><button onClick={()=>updateCartQuantity(item.id,item.quantity-1)}><Minus/></button><span>{item.quantity}</span><button onClick={()=>updateCartQuantity(item.id,item.quantity+1)}><Plus/></button></div></div><strong>${(item.price*item.quantity).toFixed(2)}</strong></div>):<div className="empty">Your bag is waiting for something beautiful.</div>}
  {needsAddress&&!addressReady&&<section className="checkout-address"><h3>Shipping address</h3>{[['street','Street address'],['city','City'],['region','State / region'],['postalCode','Postal code']].map(([key,label])=><label className="field" key={key}>{label}<input value={address[key]||''} onChange={event=>setAddress({...address,[key]:event.target.value})}/></label>)}</section>}
  <div className="order-total"><span>Total</span><b>${total.toFixed(2)}</b></div>{confirming?<><div className="confirm-note">Confirm that you want to purchase these items for <b>${total.toFixed(2)}</b>.</div><button disabled={!cart.length||(needsAddress&&!addressReady)} onClick={()=>{if(needsAddress)localStorage.setItem('socialstart-settings-address',JSON.stringify(address));setComplete(true);clearCart()}} className="primary-btn wide">Confirm purchase</button><button onClick={()=>setConfirming(false)} className="checkout-back">Back to bag</button></>:<button disabled={!cart.length||(needsAddress&&!addressReady)} onClick={()=>setConfirming(true)} className="primary-btn wide">Continue to confirm purchase</button>}</div>
}

export function ManageStorePage(){
 const imageInput=useRef<HTMLInputElement>(null),bannerInput=useRef<HTMLInputElement>(null),productUpload=useRef<Promise<string>|null>(null)
 const accountId=localStorage.getItem('socialstart-active-account')||'guest',detailsKey=`socialstart-account-store-${accountId}`
 const savedDetails=()=>{try{return JSON.parse(localStorage.getItem(detailsKey)||'{}') as AccountStore}catch{return {}}}
 const initialDetails=savedDetails()
 const [storeName,setStoreName]=useState(initialDetails.storeName||''),[description,setDescription]=useState(initialDetails.description||''),[banner,setBanner]=useState(initialDetails.banner||''),[pendingBanner,setPendingBanner]=useState(''),[detailsSaved,setDetailsSaved]=useState(false),[bannerSaved,setBannerSaved]=useState(false),[bannerMessage,setBannerMessage]=useState(''),[title,setTitle]=useState(''),[quantity,setQuantity]=useState(''),[price,setPrice]=useState(''),[productImage,setProductImage]=useState(''),[editingProductId,setEditingProductId]=useState<number|null>(null),[productEditing,setProductEditing]=useState(false),[productFilter,setProductFilter]=useState('none'),[productOverlay,setProductOverlay]=useState(''),[productOverlayX,setProductOverlayX]=useState(50),[productOverlayY,setProductOverlayY]=useState(50),[ship,setShip]=useState(true),[inPerson,setInPerson]=useState(false),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState(''),[productMessage,setProductMessage]=useState('')
 const [storeProducts,setStoreProducts]=useState<DraftProduct[]>(()=>initialDetails.products||[])
 const username=(()=>{try{return JSON.parse(localStorage.getItem('socialstart-settings-profile')||'{}').username||'creator'}catch{return 'creator'}})()
 const saveStoreRecord=(updates:Partial<AccountStore>)=>{let current:AccountStore={};try{current=JSON.parse(localStorage.getItem(detailsKey)||'{}')}catch{/* Replace damaged store data. */}const next={...current,username,storeName:storeName.trim(),description:description.trim(),banner,...updates};localStorage.setItem(detailsKey,JSON.stringify(next));scheduleCloudSave();return next}
 const saveProducts=(next:DraftProduct[])=>{setStoreProducts(next);saveStoreRecord({products:next})}
 const chooseImage=async(file?:File)=>{if(!file)return;setUploading(true);setUploadError('');setProductMessage('');try{const localImage=await persistentImage(file);setProductImage(localImage);productUpload.current=uploadMedia(localImage,'products').catch(error=>{setUploadError(error instanceof Error?`${error.message} The compressed product photo will still be saved.`:'The cloud image upload failed; the compressed photo will still be saved.');return localImage});setUploading(false)}catch(error){setUploadError(error instanceof Error?error.message:'The image could not be loaded.');setUploading(false)}}
 const resetProductForm=()=>{setEditingProductId(null);setTitle('');setQuantity('');setPrice('');setProductImage('');setProductFilter('none');setProductOverlay('');setProductOverlayX(50);setProductOverlayY(50);setShip(true);setInPerson(false);productUpload.current=null}
 const saveProduct=async()=>{if(!title||!quantity||!price||!productImage||(!ship&&!inPerson))return;setUploading(true);setProductMessage('Saving product…');let savedImage=productImage;try{if(productUpload.current)savedImage=await productUpload.current}catch{/* The compressed image remains persistent if cloud media storage is unavailable. */}const product:DraftProduct={id:editingProductId||Date.now(),title:title.trim(),quantity:Number(quantity),price:Number(price),image:savedImage,ship,inPerson,mediaFilter:productFilter,overlayText:productOverlay.trim()||undefined,overlayX:productOverlayX,overlayY:productOverlayY},next=editingProductId?storeProducts.map(item=>item.id===editingProductId?product:item):[...storeProducts,product];saveProducts(next);resetProductForm();setProductMessage(editingProductId?'Product changes saved.':'Product added and saved.');setUploading(false)}
 const editProduct=(product:DraftProduct)=>{setEditingProductId(product.id);setTitle(product.title);setQuantity(String(product.quantity));setPrice(String(product.price));setProductImage(product.image);setProductFilter(product.mediaFilter||'none');setProductOverlay(product.overlayText||'');setProductOverlayX(product.overlayX??50);setProductOverlayY(product.overlayY??50);setShip(Boolean(product.ship));setInPerson(Boolean(product.inPerson));setProductMessage('');productUpload.current=null;document.querySelector('.product-form-panel')?.scrollIntoView({behavior:'smooth',block:'start'})}
 const saveDetails=()=>{saveStoreRecord({});setStoreName(storeName.trim());setDescription(description.trim());setDetailsSaved(true)}
 const chooseBanner=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas'),scale=Math.min(1,900/image.width,320/image.height);canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height);setPendingBanner(canvas.toDataURL('image/jpeg',.55));setBannerSaved(false);setBannerMessage('Banner ready — click Save banner.')} ;image.src=String(reader.result)};reader.readAsDataURL(file)}
 const saveBanner=async()=>{if(!pendingBanner)return;setUploading(true);setUploadError('');setBannerMessage('Saving banner…');let savedImage=pendingBanner;try{savedImage=await uploadMedia(pendingBanner,'store-banners')}catch{/* Keep the compressed persistent image when cloud upload is unavailable. */}setBanner(savedImage);const record=saveStoreRecord({banner:savedImage,products:storeProducts});localStorage.setItem(`socialstart-store-banner-${accountId}`,savedImage);try{await saveStoreNow(record as Record<string,unknown>)}catch(error){setUploadError(error instanceof Error?`The banner is saved on this device, but cloud sync needs another try: ${error.message}`:'The banner is saved on this device, but cloud sync needs another try.')}setPendingBanner('');setBannerSaved(true);setBannerMessage('Banner saved successfully.');setUploading(false)}
 const visibleBanner=pendingBanner||banner
 return <div className="manage-store-page"><section className={`store-setup-header store-banner-wide${visibleBanner?' has-banner':''}`} style={visibleBanner?{backgroundImage:`linear-gradient(90deg,rgba(73,16,37,.82),rgba(73,16,37,.5)),url("${mediaUrl(visibleBanner)}")`}:undefined}><div><p className="eyebrow">YOUR ONLINE STORE</p><h1>{storeName||'Build your store'}</h1><p>{description||'Add a name and a short line that tells shoppers what makes your store special.'}</p></div><div className="banner-actions"><input ref={bannerInput} hidden type="file" accept="image/*" onChange={event=>chooseBanner(event.target.files?.[0])}/><button type="button" className="banner-edit" onClick={()=>bannerInput.current?.click()}><ImagePlus/> Edit banner</button>{(pendingBanner||bannerSaved)&&<button type="button" className={bannerSaved?'banner-save saved':'banner-save'} disabled={bannerSaved||uploading} onClick={saveBanner}><Save/> {bannerSaved?'Banner saved':'Save banner'}</button>}</div></section>
  {uploadError&&<p className="camera-error">{uploadError}</p>}<section className="store-editor"><div className="store-form"><p className="eyebrow">STORE DETAILS</p><h2>Name your shop</h2><label className="field">Store name<input value={storeName} onChange={e=>{setStoreName(e.target.value);setDetailsSaved(false)}}/></label><label className="field">Line under store name<textarea value={description} onChange={e=>{setDescription(e.target.value);setDetailsSaved(false)}}/></label><button type="button" className="secondary-btn" onClick={saveDetails}><Save/> Save store details</button>{detailsSaved&&<p className="save-success">Store details saved.</p>}</div>
  <div className="product-form-panel"><p className="eyebrow">{editingProductId?'EDIT PRODUCT':'ADD A PRODUCT'}</p><h2>{editingProductId?'Update your listing':'Your first listing'}</h2><input ref={imageInput} hidden type="file" accept="image/*" onChange={e=>chooseImage(e.target.files?.[0])}/><button type="button" disabled={uploading} onClick={()=>imageInput.current?.click()} className="product-image-drop">{productImage?<div className="editable-media-preview"><img src={mediaUrl(productImage)} alt="Product preview" style={{filter:productFilter}}/>{productOverlay&&<span style={{left:`${productOverlayX}%`,top:`${productOverlayY}%`}}>{productOverlay}</span>}</div>:<><ImagePlus/><b>{uploading?'Preparing…':'Add product photo'}</b><span>Upload a clear image of your product</span></>}</button>{productImage&&<div className="media-edit-row"><button type="button" className="secondary-btn media-edit-button" onClick={()=>setProductEditing(true)}><Pencil/> Edit image</button></div>}<label className="field">Product title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="field-pair"><label className="field">Quantity<input min="1" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label className="field">Price<input min="0" step="0.01" type="number" value={price} onChange={e=>setPrice(e.target.value)}/></label></div><div className="fulfillment-switches"><button type="button" className={ship?'active':''} onClick={()=>setShip(!ship)}><i className={ship?'switch on':'switch'}><i/></i> Ship</button><button type="button" className={inPerson?'active':''} onClick={()=>setInPerson(!inPerson)}><i className={inPerson?'switch on':'switch'}><i/></i> In Person</button></div>{!ship&&!inPerson&&<p className="camera-error">Select Ship, In Person, or both.</p>}<button type="button" onClick={()=>void saveProduct()} disabled={uploading||!title||!quantity||!price||!productImage||(!ship&&!inPerson)} className="primary-btn wide">{uploading?'Saving…':editingProductId?'Save product changes':'Add product'}</button>{editingProductId&&<button type="button" className="secondary-btn wide cancel-product-edit" onClick={resetProductForm}>Cancel editing</button>}{productMessage&&<p className="save-success">{productMessage}</p>}</div></section>
  {productEditing&&<div className="purchase-modal media-editor-modal"><div><button className="modal-close" onClick={()=>setProductEditing(false)}><X/></button><Pencil/><h2>Edit product image</h2><div className="editor-preview"><img src={mediaUrl(productImage)} style={{filter:productFilter}}/>{productOverlay&&<span style={{left:`${productOverlayX}%`,top:`${productOverlayY}%`}}>{productOverlay}</span>}</div><label className="field">Look<select value={productFilter} onChange={event=>setProductFilter(event.target.value)}><option value="none">Original</option><option value="grayscale(1)">Black & white</option><option value="sepia(.75)">Warm</option><option value="saturate(1.5)">Vivid</option><option value="brightness(1.15)">Bright</option><option value="contrast(1.35)">High contrast</option><option value="hue-rotate(25deg)">Golden</option><option value="hue-rotate(170deg)">Cool</option><option value="saturate(.55)">Muted</option><option value="brightness(.82) contrast(1.2)">Moody</option></select></label><label className="field">Text overlay<input maxLength={80} value={productOverlay} onChange={event=>setProductOverlay(event.target.value)} placeholder="Add text…"/></label><div className="field-pair"><label className="field">Horizontal position<input type="range" min="8" max="92" value={productOverlayX} onChange={event=>setProductOverlayX(Number(event.target.value))}/></label><label className="field">Vertical position<input type="range" min="8" max="92" value={productOverlayY} onChange={event=>setProductOverlayY(Number(event.target.value))}/></label></div><button className="primary-btn wide" onClick={()=>setProductEditing(false)}>Apply edits</button></div></div>}
  <section className="store-products"><p className="eyebrow">YOUR PRODUCTS · {formatCount(storeProducts.length)}</p>{storeProducts.length===0?<div className="profile-empty"><ShoppingBag/><h3>No products yet</h3><p>Add your first product using the form above.</p></div>:<div className="draft-products">{storeProducts.map(product=><article key={product.id}><img src={mediaUrl(product.image)} alt=""/><div><b>{product.title}</b><span>{formatCount(product.quantity)} available</span></div><strong>{formatCurrency(product.price)}</strong><div className="product-row-actions"><button className="edit-product" onClick={()=>editProduct(product)}><Pencil/> Edit</button><button className="delete-product" onClick={()=>saveProducts(storeProducts.filter(item=>item.id!==product.id))}><Trash2/> Delete</button></div></article>)}</div>}</section>
 </div>
}
