import { useState } from 'react'
import { Bookmark, Gift, Heart, Maximize, MessageCircle, MoreHorizontal, Send, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import type { Post } from '../types'
export function PostCard({post}:{post:Post}){
 const {isPostSaved,toggleSavedPost,likedPostIds,togglePostLike,followingUsernames,toggleFollow,recordShare,points,donatePoints}=useApp()
 const [shared,setShared]=useState(false),[fullscreen,setFullscreen]=useState(false),[donating,setDonating]=useState(false),[donation,setDonation]=useState(1),[donationMessage,setDonationMessage]=useState('')
 const liked=likedPostIds.includes(post.id),saved=isPostSaved(post.id),following=followingUsernames.includes(post.username)
 const share=async()=>{const url=`${window.location.origin}/post/${post.id}`;try{if(navigator.share)await navigator.share({title:post.title,text:`See ${post.author}'s post on SocialStart`,url});else await navigator.clipboard.writeText(url);recordShare();setShared(true);window.setTimeout(()=>setShared(false),2200)}catch{/* User cancelled sharing. */}}
 const media=post.mediaType==='video'||post.mediaType==='live'?<video src={post.image} controls={fullscreen||post.mediaType==='live'} autoPlay loop muted playsInline/>:<img src={post.image} alt={post.title}/>
 const donate=()=>{if(donatePoints(post.username,donation)){setDonationMessage(`${donation} point${donation===1?'':'s'} donated to @${post.username}.`);setDonating(false)}else setDonationMessage('You do not have enough Social Points.')}
 return <article className="post-card"><div className="post-owner"><Link to={`/profile/${post.username}`}><img src={post.avatar}/></Link><div><Link to={`/profile/${post.username}`}><b>{post.author}</b></Link><span>{post.location} · {post.followers} followers</span></div>{post.username!=='alexmorgan'&&<button className={following?'follow following':'follow'} onClick={()=>toggleFollow(post.username)}>{following?'Following':'Follow'}</button>}<button className="plain"><MoreHorizontal/></button></div>
  <div className="media-wrap"><Link to={`/post/${post.id}`} className="media-content">{media}<span className={post.mediaType==='live'?'media-label live-label':'media-label'}>{post.mediaType==='live'?'● LIVE':post.username==='alexmorgan'?'YOUR POST':'FEATURED'}</span>{post.mediaType==='live'&&<span className="live-viewers">{post.views} watching</span>}</Link><button className="post-fullscreen" onClick={()=>setFullscreen(true)}><Maximize/></button></div>
  <div className="post-actions"><div><button onClick={()=>togglePostLike(post.id)} className={liked?'liked':''}><Heart fill={liked?'currentColor':'none'}/></button><Link className="post-action-link" to={`/post/${post.id}`}><MessageCircle/></Link><button onClick={share}><Send/></button></div>{post.username!=='alexmorgan'&&<button onClick={()=>setDonating(!donating)} aria-label="Donate Social Points"><Gift/></button>}<button onClick={()=>toggleSavedPost(post)}><Bookmark fill={saved?'currentColor':'none'}/></button></div>
  {donating&&<div className="donation-panel"><span>You have {points} Social Points</span><input aria-label="Points to donate" type="number" min="1" max={points} value={donation} onChange={event=>setDonation(Math.max(1,Number(event.target.value)))}/><button disabled={points<1||donation>points} onClick={donate}>Donate</button></div>}{donationMessage&&<div className="share-success">{donationMessage}</div>}{shared&&<div className="share-success">Post link copied — ready to share.</div>}<div className="post-copy"><b>{(post.likes+(liked?1:0)).toLocaleString()} likes</b><p><strong>@{post.username}</strong> {post.title}</p><span>{post.views} views · View comments</span></div>
  {fullscreen&&<div className="fullscreen-overlay"><button onClick={()=>setFullscreen(false)}><X/></button>{media}<div><b>@{post.username}</b><span>{post.title}</span></div></div>}
 </article>
}
