import { useEffect, useState } from 'react'
import { Bookmark, Gift, Heart, Lock, Maximize, Send, Trash2, Unlock, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import type { Post } from '../types'
import { SharePostModal } from './SharePostModal'
import { activeMembershipFor, membershipPlanFor } from '../lib/memberships'
import { formatCount, parseCount } from '../lib/format'
import { extractHashtags } from '../lib/hashtags'
export function PostCard({post,ownerView=false,profileView=false}:{post:Post;ownerView?:boolean;profileView?:boolean}){
 const app=useApp()
 const {isPostSaved,toggleSavedPost,likedPostIds,togglePostLike,followingUsernames,toggleFollow,recordShare,viewPost,postMetrics,viewPoints,giftViewPoints,deletePost,lockedPosts,setPostPrice,unlockPost,purchasedPostIds,purchasePost,balance,spendBalance}=app
 const [shared,setShared]=useState(false),[shareDialog,setShareDialog]=useState(false),[fullscreen,setFullscreen]=useState(false),[donating,setDonating]=useState(false),[donation,setDonation]=useState(1),[giftType,setGiftType]=useState<'image'|'video'>('image'),[donationMessage,setDonationMessage]=useState(''),[deleteDialog,setDeleteDialog]=useState(false),[priceDialog,setPriceDialog]=useState(false),[purchaseDialog,setPurchaseDialog]=useState(false),[cardCheckout,setCardCheckout]=useState(false),[price,setPrice]=useState(1),[card,setCard]=useState({cardName:'',cardNumber:'',expiry:'',cvv:''})
 const readOwnProfile=()=>{try{return JSON.parse(localStorage.getItem('socialstart-settings-profile')||'{}') as {avatar?:string;name?:string;username?:string}}catch{return {}}}
 const [ownProfile,setOwnProfile]=useState(readOwnProfile)
 useEffect(()=>{const update=()=>setOwnProfile(readOwnProfile());window.addEventListener('socialstart-profile-updated',update);return()=>window.removeEventListener('socialstart-profile-updated',update)},[])
 useEffect(()=>{
  if(ownerView||profileView)return
  const card=Array.from(document.querySelectorAll<HTMLAnchorElement>('a')).find(link=>link.getAttribute('href')===`/post/${post.id}`)?.closest('article')
  if(!card)return
  const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting&&entry.intersectionRatio>=.55)){viewPost(post.id);observer.disconnect()}},{threshold:.55})
  observer.observe(card)
  return()=>observer.disconnect()
 },[ownerView,profileView,post.id])
 const membership=membershipPlanFor(post.username),liked=likedPostIds.includes(post.id),metric=postMetrics[post.id]||{likes:0,views:0},saved=isPostSaved(post.id),following=followingUsernames.includes(post.username),lockedPrice=lockedPosts[post.id]??post.lockedPrice
 const displayHashtags=[...new Set([...(post.hashtags||[]),...extractHashtags(post.title)])].slice(0,5)
 const activeAccount=localStorage.getItem('socialstart-active-account'),isOwnPost=post.ownerAccountId===activeAccount||Boolean(ownProfile.username&&post.username===ownProfile.username),accessible=ownerView||isOwnPost||Boolean(activeMembershipFor(post.username))||(!membership&&!lockedPrice)||purchasedPostIds.includes(post.id),displayAvatar=isOwnPost&&ownProfile.avatar?ownProfile.avatar:post.avatar,displayName=isOwnPost&&ownProfile.name?ownProfile.name:post.author,displayUsername=isOwnPost&&ownProfile.username?ownProfile.username:post.username,profileHref=isOwnPost?'/profile':`/profile/${post.ownerAccountId||post.username}`
 const share=async()=>{const url=`${window.location.origin}/post/${post.id}`;try{if(navigator.share)await navigator.share({title:post.title,text:`See ${post.author}'s post on SocialStart`,url});else await navigator.clipboard.writeText(url);recordShare();setShared(true);window.setTimeout(()=>setShared(false),2200)}catch{/* User cancelled sharing. */}}
 const media=post.mediaType==='video'||post.mediaType==='live'?<video src={post.image} controls={fullscreen||post.mediaType==='live'} autoPlay loop muted playsInline onClick={event=>{event.currentTarget.muted=false;void event.currentTarget.play()}}/>:<img src={post.image} alt={post.title}/>
 const mediaDetails=<>{media}{!ownerView&&<span className={post.mediaType==='live'?'media-label live-label':'media-label'}>{post.mediaType==='live'?'● LIVE':post.username==='alexmorgan'?'YOUR POST':'FEATURED'}</span>}{post.mediaType==='live'&&<span className="live-viewers">{post.views} watching</span>}</>
 const donate=()=>{if(giftViewPoints(post.username,giftType,donation)){setDonationMessage(`${donation} ${giftType} view point${donation===1?'':'s'} gifted to @${post.username}.`);setDonating(false)}else setDonationMessage(`You do not have enough ${giftType} view points.`)}
 if(profileView)return <article className="post-card profile-post-tile"><div className="profile-post-title">{post.title}</div><div className={`media-wrap${accessible?'':' locked-media'}`}>{accessible?<Link to={`/post/${post.id}`} className="media-content">{media}</Link>:<Link className="media-content purchase-gate" to={membership?`/membership/${post.username}/checkout`:`/post/${post.id}`}>{media}<strong><Lock/> {membership?`Membership · $${membership.price.toFixed(2)}/month`:`Purchase to view · $${lockedPrice?.toFixed(2)}`}</strong></Link>}</div></article>
 return <article className="post-card"><div className="post-owner">{ownerView?<img src={displayAvatar}/>:<Link to={profileHref}><img src={displayAvatar}/></Link>}<div>{ownerView?<b>{displayName}</b>:<Link to={profileHref}><b>{displayName}</b></Link>}<span>{post.location} · {post.followers} followers</span></div>{!isOwnPost&&<button className={following?'follow following':'follow'} onClick={()=>toggleFollow(post.username)}>{following?'Following':'Follow'}</button>}</div>
  <div className={`media-wrap${accessible?'':' locked-media'}`}>{accessible?<Link to={`/post/${post.id}`} className="media-content">{mediaDetails}</Link>:<button className="media-content purchase-gate" onClick={()=>membership?window.location.assign(`/profile/${post.username}`):setPurchaseDialog(true)}>{mediaDetails}<strong><Lock/> {membership?`Membership · $${membership.price.toFixed(2)}/month`:`Purchase to view · $${lockedPrice?.toFixed(2)}`}</strong></button>}<button className="post-fullscreen" disabled={!accessible} onClick={()=>setFullscreen(true)}><Maximize/></button>{ownerView&&<button className="post-lock" onClick={()=>lockedPrice?unlockPost(post.id):setPriceDialog(true)}><Lock/><span>{lockedPrice?'Locked':'Lock'}</span></button>}</div>
  <div className="post-actions"><div><button onClick={()=>togglePostLike(post.id)} className={liked?'liked':''}><Heart fill={liked?'currentColor':'none'}/></button><button onClick={()=>setShareDialog(true)}><Send/></button></div>{!isOwnPost&&<button onClick={()=>setDonating(!donating)} aria-label="Gift view points"><Gift/></button>}{isOwnPost&&<button onClick={()=>setDeleteDialog(true)} aria-label="Delete post"><Trash2/></button>}<button onClick={()=>toggleSavedPost(post)} aria-label={saved?'Remove saved post':'Save post'}><Bookmark fill={saved?'currentColor':'none'}/></button></div>
  {donating&&<div className="donation-panel"><span>Gift view points</span><select value={giftType} onChange={event=>setGiftType(event.target.value as 'image'|'video')}><option value="image">Photo view points ({formatCount(viewPoints.image)})</option><option value="video">Video view points ({formatCount(viewPoints.video)})</option></select><input type="number" min="1" max={viewPoints[giftType]} value={donation} onChange={event=>setDonation(Math.max(1,Number(event.target.value)))}/><button disabled={viewPoints[giftType]<1||donation>viewPoints[giftType]} onClick={donate}>Gift</button></div>}{donationMessage&&<div className="share-success">{donationMessage}</div>}{shared&&<div className="share-success">Post link copied — ready to share.</div>}<div className="post-copy"><b>{formatCount(post.likes+metric.likes)} likes</b><p><strong>@{displayUsername}</strong> {post.title}</p><span>{formatCount(parseCount(post.views)+metric.views)} views · View comments</span>{displayHashtags.length>0&&<div className="post-hashtag-links">{displayHashtags.map(tag=><Link to={`/hashtag/${encodeURIComponent(tag)}`} key={tag}>#{tag}</Link>)}</div>}</div>
  {fullscreen&&<div className="fullscreen-overlay"><button onClick={()=>setFullscreen(false)}><X/></button>{media}<div><b>@{displayUsername}</b><span>{post.title}</span></div></div>}
  {priceDialog&&<div className="purchase-modal"><div><button className="modal-close" onClick={()=>setPriceDialog(false)}><X/></button><Unlock/><h2>Lock this post</h2><p>Choose the price someone must pay before viewing.</p><label>Price<input type="number" min=".01" step=".01" value={price} onChange={event=>setPrice(Number(event.target.value))}/></label><button className="primary-btn wide" disabled={price<=0} onClick={()=>{setPostPrice(post.id,price);setPriceDialog(false)}}>Lock for ${price.toFixed(2)}</button></div></div>}
  {deleteDialog&&<div className="purchase-modal"><div><button className="modal-close" onClick={()=>setDeleteDialog(false)}><X/></button><Trash2/><h2>Delete this post everywhere?</h2><p>This removes the post from your profile, search, saved posts, and hashtag pages. This cannot be undone.</p><button className="delete-group-button wide" onClick={()=>{deletePost(post.id);setDeleteDialog(false)}}><Trash2/> Delete post</button><button className="secondary-btn wide" onClick={()=>setDeleteDialog(false)}>Cancel</button></div></div>}
  {purchaseDialog&&<div className="purchase-modal"><div><button className="modal-close" onClick={()=>{setPurchaseDialog(false);setCardCheckout(false)}}><X/></button><Lock/><h2>{cardCheckout?'Pay by card':'Purchase this post'}</h2><p>Unlock @{post.username}’s post for ${lockedPrice?.toFixed(2)}.</p>{cardCheckout?<form className="card-checkout" onSubmit={event=>{event.preventDefault();localStorage.setItem('socialstart-settings-billing',JSON.stringify(card));purchasePost(post.id);setPurchaseDialog(false);setCardCheckout(false)}}><label>Name on card<input required value={card.cardName} onChange={event=>setCard({...card,cardName:event.target.value})}/></label><label>Card number<input required inputMode="numeric" value={card.cardNumber} onChange={event=>setCard({...card,cardNumber:event.target.value})}/></label><div><label>Expiration<input required placeholder="MM/YY" value={card.expiry} onChange={event=>setCard({...card,expiry:event.target.value})}/></label><label>Security code<input required inputMode="numeric" value={card.cvv} onChange={event=>setCard({...card,cvv:event.target.value})}/></label></div><button className="primary-btn wide" type="submit">Purchase ${lockedPrice?.toFixed(2)}</button></form>:<><p className="wallet-available">Wallet balance: ${balance.toFixed(2)}</p><button className="primary-btn wide" onClick={()=>{if(lockedPrice&&spendBalance(lockedPrice)){purchasePost(post.id);setPurchaseDialog(false)}else setCardCheckout(true)}}>{lockedPrice&&balance>=lockedPrice?'Purchase with wallet':'Continue to card'}</button></>}</div></div>}
  {shareDialog&&<SharePostModal post={post} onClose={()=>setShareDialog(false)} onShared={()=>{recordShare();setShareDialog(false);setShared(true);window.setTimeout(()=>setShared(false),2200)}}/>}
 </article>
}
