import { useRef, useState } from 'react'
import { Camera, Image, Radio, Repeat2, Upload, Video, X } from 'lucide-react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
const choices=[['/create/photo','Take picture',Camera,'Open your camera and capture the moment'],['/create/video','Take video',Video,'Record something worth sharing'],['/create/story','Add story',Repeat2,'Share a moment for 24 hours'],['/create/post','Create post',Image,'Upload a photo or video'],['/create/one-for-one','One For One',Upload,'Promote and earn Social Points'],['/create/live','Go live',Radio,'Broadcast to your community']] as const
export function CreateHubPage(){return <div className="create-page"><p className="eyebrow">START SOMETHING</p><h1>What will you<br/><em>share today?</em></h1><div className="create-grid">{choices.map(([to,title,Icon,desc],i)=><Link to={to} key={to} className={i===4?'accent':''}><Icon/><b>{title}</b><span>{desc}</span><i>0{i+1}</i></Link>)}</div></div>}
export function MediaCreatePage(){
 const location=useLocation(),navigate=useNavigate(),input=useRef<HTMLInputElement>(null),[preview,setPreview]=useState(''),[title,setTitle]=useState('')
 const kind=location.pathname.includes('story')?'Story':location.pathname.includes('video')?'Video':location.pathname.includes('photo')?'Photo':'Post'
 return <div className="form-page"><p className="eyebrow">CREATE / {kind.toUpperCase()}</p><h1>Share a new {kind.toLowerCase()}</h1><div onClick={()=>input.current?.click()} className="upload-drop">{preview?<img src={preview}/>:<><Upload/><b>Choose {kind==='Video'?'a video':'photo or video'}</b><span>Tap to browse from your device</span></>}<input ref={input} hidden type="file" accept={kind==='Video'?'video/*':'image/*,video/*'} onChange={e=>{const f=e.target.files?.[0];if(f)setPreview(URL.createObjectURL(f))}}/></div><label className="field">Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Give your post a title…"/></label>{kind==='Story'&&<p className="form-note">Your story will disappear after 24 hours.</p>}<div className="form-actions"><button className="secondary-btn" onClick={()=>navigate('/create')}><X/> Cancel</button><button className="primary-btn" disabled={!preview} onClick={()=>navigate('/profile')}>Share {kind}</button></div></div>
}
export function OneForOnePage(){return <div className="create-page"><p className="eyebrow">ONE FOR ONE</p><h1>Share attention.<br/><em>Earn attention.</em></h1><p className="lead">Watch a creator’s promo and earn a point. Spend your points to put your own work in front of someone new.</p><div className="create-grid two"><Link to="/create/one-for-one/upload"><Upload/><b>Add a promo</b><span>Upload a video up to 30 seconds</span></Link><Link className="accent" to="/create/one-for-one/earn"><Video/><b>Earn Social Points</b><span>Watch promos from other creators</span></Link></div></div>}
export function EarnPointsPage(){const [progress,setProgress]=useState(0);return <div className="form-page centered"><p className="eyebrow">EARN SOCIAL POINTS</p><h1>Discover something new</h1><div className="promo-card"><img src={postsImage}/><button onClick={()=>setProgress(100)}>{progress===100?'✓ Point earned':'▶ Watch promo'}</button><div><b>Sunday Studio</b><span>Meet the makers behind every piece.</span></div></div><div className="progress"><i style={{width:`${progress}%`}}/></div><p>{progress}% complete · Keep this window active</p></div>}
const postsImage='https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=1000&auto=format&fit=crop'
